worker_num: 4
TrainReader:
  sample_transforms:
    - Decode: {}
    - RandomFlip: {prob: 0.5}
    - RandomDistort: {}
    - PPMosaic: {target_size: 640}
  batch_transforms:
    - NormalizeImage: {mean: [ 0.485, 0.456, 0.406 ], std: [ 0.229, 0.224, 0.225 ], is_scale: True}
    - Permute: {}
    - PadBatch: {pad_to_stride: 32}
  batch_size: 8
  shuffle: true
  drop_last: true
  mosaic_epoch: 170
  mixup_epoch: 170
  use_shared_memory: false
  collate_batch: false

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: 640, keep_ratio: True}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_transforms:
    - PadBatch: {pad_to_stride: 32}
  batch_size: 4

TestReader:
  inputs_def:
    image_shape: [3, -1, -1]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: 640, keep_ratio: True}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_transforms:
    - PadBatch: {pad_to_stride: 32}
  batch_size: 1
