epoch: 300

LearningRate:
  base_lr: 0.01
  schedulers:
  - !CosineDecay
    max_epochs: 360
#    eta_min: 0.0005
  - !LinearWarmup
    start_factor: 0.001
    steps: 4000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2
