_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  './_base_/ppyolov2_r50vd_dcn.yml',
  './_base_/optimizer_365e.yml',
  './_base_/ppyolov2_reader.yml',
]

norm_type: sync_bn
use_ema: true
ema_decay: 0.9998

snapshot_epoch: 1
log_iter: 10

weights: output/ppyolov2_r50vd_dynamic_1x_minicoco/model_final

YOLOv3:
  backbone: ResNet
  neck: DynamicHead
  yolo_head: YOLOv3Head
  post_process: BBoxPostProcess

ResNet:
  depth: 50
  variant: d
  return_idx: [1, 2, 3]
  freeze_at: -1
  freeze_norm: false
  norm_decay: 0.

DynamicHead:
  num_heads: 6
  mid_layer_idx: 
  use_fpn: true
  out_channels: 256


worker_num: 4
TrainReader:
  batch_size: 8

EvalReader:
  batch_size: 1


TrainDataset:
  !COCODataSet
    image_dir: train2017
    anno_path: annotations/instances_minitrain2017.json
    dataset_dir: dataset/coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

epoch: 150

LearningRate:
  # base_lr: 0.005
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    # - 153
    # - 173
    - 120
  - !LinearWarmup
    start_factor: 0.
    # steps: 4000
    steps: 2000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2


