_BASE_: [
  '../datasets/plain.yml',
  '../runtime.yml',
  './_base_/ppyolov2_r50vd_dcn.yml',
  './_base_/ppyolov2_reader.yml',
]



num_classes: 80


TrainDataset:
  !PlainDetDataSet
    dataset_dir: dataset
    anno_path: ['coco/annotations/instances_train2017.json.csv',
                'obj365/annos/zhiyuan_objv2_train.json.csv', 
                'oid/annos/oidv6-train-annotations-bbox.csv-tmp.csv']

    data_fields: ['image', 'gt_bbox', 'gt_class',]
    use_cache: True


snapshot_epoch: 2
weights: output/lst_ppyolo_r50vd_dcn/model_final


epoch: 36
LearningRate:
  base_lr: 0.005
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 24
  - !LinearWarmup
    start_factor: 0.
    steps: 5000

OptimizerBuilder:
  clip_grad_by_norm: 35.
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2
