_BASE_: [
  '../runtime.yml',
  './lst_dataset.yml',
  './_base_/ppyolov2_r50vd_dcn.yml',
]



num_classes: 800

snapshot_epoch: 2
weights: output/lst_ppyolo_r50vd_dcn/model_final


epoch: 24 # 24 # 36 53-day
LearningRate:
  # base_lr: 0.005 # 0.0075
  base_lr: 0.0075 # 0.0075
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 16 # 16 # 24
  - !LinearWarmup
    start_factor: 0.
    steps: 10000

OptimizerBuilder:
  clip_grad_by_norm: 35.
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2
