worker_num: 2
TrainReader:    
  sample_transforms:
    - Decode: {}
    
    - Resize: {target_size: [640], keep_ratio: True, interp: 2}
    
    - RandomResize: {target_size: [640], random_interp: True, keep_ratio: True}
    - Mosaic: {target_size: 640, mosaic_border: [-320, -320]} #  # x y w h 
    - RandomPerspective: {degree: 0, translate: 0.1, scale: 0.5, shear: 0.0, perspective: 0.0, border: [-320, -320]} # x y w h 
    
#     - RandomResize: {target_size: [960], random_interp: True, keep_ratio: True}
#     - Mosaic: {target_size: 960, mosaic_border: [-480, -480]} #  # x y w h 
#     - RandomPerspective: {degree: 0, translate: 0.1, scale: 0.5, shear: 0.0, perspective: 0.0, border: [-480, -480]} # x y w h 

    # - RandomResize: {target_size: [640], random_interp: True, keep_ratio: False}
    
    - RandomFlip: {prob: 0.5}
    # - RandomHSV: {hgain: 0.015, sgain: 0.7, vgain: 0.4}
    
    - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
    - Permute: {}
    
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  - Gt2GFLTarget:
      downsample_ratios: [8, 16, 32, 64, 128]
      grid_cell_scale: 8
      
  batch_size: 2  
  mosaic_epoch: 10000
  shuffle: true
  drop_last: true
  use_shared_memory: false


EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: False, interp: 2}
    # - Resize: {target_size: [640], keep_ratio: True, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_transforms:
    - PadBatch: {pad_to_stride: 32}
  batch_size: 2
  shuffle: false
  
