_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  './_base_/base_reader.yml',
]

log_iter: 100
snapshot_epoch: 2
weights: output/refineT_yolo_convnext_coco_3x/model_final
find_unused_parameters: True


architecture: YOLOv3
norm_type: sync_bn
use_ema: true
ema_decay: 0.9998

YOLOv3:
  backbone: ConvNeXt
  neck: CustomCSPPAN
  yolo_head: PPRefineTHead
  post_process: ~

ConvNeXt:
  depths: [ 3, 3, 9, 3 ]
  dims: [ 96, 192, 384, 768 ]
  return_idx: [ 1, 2, 3 ]
  drop_path_rate: 0.4
  layer_scale_init_value: 1.0
  pretrained: /paddle/convnext_tiny_1k_224_ema.params

CustomCSPPAN:
  out_channels: [768, 384, 192]
  stage_num: 1
  block_num: 3
  act: 'swish'
  block_fn: 'BasicBlock'
  block_size: 3
  keep_prob: 0.9
  spp: true

PPRefineTHead:
  fpn_strides: [32, 16, 8]
  grid_cell_scale: 5.0
  grid_cell_offset: 0.5
  loss_weight: {class: 1.0, iou: 1.0, iou_r: 2.0}
  static_assigner_epoch: 4
  use_varifocal_loss: True
  static_assigner:
    name: ATSSAssigner
    topk: 9
    force_gt_matching: False
  assigner:
    name: TaskAlignedAssigner
    topk: 13
    alpha: 1.0
    beta: 6.0
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 100
    score_threshold: 0.05
    nms_threshold: 0.6

epoch: 36

LearningRate:
  base_lr: 0.0003
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [ 400 ]
    use_warmup: false

OptimizerBuilder:
  regularizer: false
  optimizer:
    type: AdamW
    weight_decay: 0.0005
