_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  './_base_/mosaic_reader.yml',
  './_base_/optimizer_180e.yml',
]

log_iter: 100
snapshot_epoch: 8
weights: output/simY_m_yolo_crn_coco_180e/model_final
find_unused_parameters: True


architecture: YOLOv3
#pretrain_weights: http://10.255.134.13:8091/weights/cspresnetb50_silu_797.pdparams
norm_type: sync_bn
use_ema: true
ema_decay: 0.9998

YOLOv3:
  backbone: CSPResNet
  neck: CustomCSPPAN
  yolo_head: PPSimYHead
  post_process: ~

CSPResNet:
  layers: [3, 6, 6, 3]
  channels: [64, 128, 256, 512, 1024]
  return_idx: [1, 2, 3]

CustomCSPPAN:
  out_channels: [768, 384, 192]
  stage_num: 1
  block_num: 3
  act: 'mish'
  block_fn: 'BasicBlock'
  block_size: 3
  keep_prob: 0.9
  spp: true

PPSimYHead:
  fpn_strides: [32, 16, 8]
  grid_cell_scale: 5.0
  grid_cell_offset: 0.5
  loss_weight: {obj: 1.0, class: 1.0, iou: 2.5}
  static_assigner_epoch: 60
  use_varifocal_loss: True
  use_align_head: True
  static_assigner:
    name: ATSSAssigner
    topk: 9
    force_gt_matching: False
  assigner:
    name: TaskAlignedAssigner
    topk: 13
    alpha: 1.0
    beta: 6.0
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 100
    score_threshold: 0.05
    nms_threshold: 0.6
