_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  './_base_/base_reader.yml',
  # './_base_/optimizer_180e.yml',
]

log_iter: 20
snapshot_epoch: 4
weights: output/test/model_final
find_unused_parameters: True


architecture: YOLOv3
# pretrain_weights: http://10.255.134.13:8091/weights/cspresnetb50_silu_797.pdparams
norm_type: sync_bn
use_ema: true
ema_decay: 0.9998


YOLOv3:
  backbone: ConvNeXt
  neck: PPYOLOPAN
  yolo_head: PPSimTHead
  post_process: ~

ConvNeXt:
  depths: [3, 3, 9, 3]
  dims: [96, 192, 384, 768]
  return_idx: [1, 2, 3]
  drop_path_rate: 0.4
  layer_scale_init_value: 1.0
  pretrained: /paddle/workspace/speed/PaddleDetection/convnext_tiny_1k_224_ema.params

ResNet:
  # index 0 stands for res2
  depth: 50
  norm_type: bn
  freeze_at: 0
  return_idx: [0,1,2]
  num_stages: 3
  
  
# CustomCSPPAN:
#   out_channels: [768, 384, 192]
#   stage_num: 1
#   block_num: 3
#   act: 'mish'
#   block_fn: 'BasicBlock'
#   block_size: 3
#   keep_prob: 0.9
#   spp: true


PPYOLOPAN:
  in_channels: [192, 384, 768]
  drop_block: true
  block_size: 3
  keep_prob: 0.9
  spp: true
  act: 'mish'
  
PPSimTHead:
  fpn_strides: [32, 16, 8]
  grid_cell_scale: 5.0
  grid_cell_offset: 0.5
  loss_weight: {class: 1.0, iou: 2.0}
  static_assigner_epoch: 4
  use_varifocal_loss: True
  static_assigner:
    name: ATSSAssigner
    topk: 9
    force_gt_matching: False
  assigner:
    name: TaskAlignedAssigner
    topk: 13
    alpha: 1.0
    beta: 6.0
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 100
    score_threshold: 0.05
    nms_threshold: 0.6



epoch: 36

LearningRate:
  base_lr: 0.001
  schedulers:
#  - !PiecewiseDecay
#    gamma: 0.1
#    milestones: [24, 33]
  - !CosineDecay
    max_epochs: 43
#    eta_min: 0.0005
  - !LinearWarmup
    start_factor: 0.001
    steps: 2000


# epoch: 180

# LearningRate:
#   base_lr: 0.01
#   schedulers:
# #  - !PiecewiseDecay
# #    gamma: 0.1
# #    milestones: [120]
#   - !CosineDecay
#     max_epochs: 216
# #    eta_min: 0.0005
#   - !LinearWarmup
#     start_factor: 0.001
#     steps: 2000

# OptimizerBuilder:
#   optimizer:
#     momentum: 0.9
#     type: Momentum
#   regularizer:
#     factor: 0.0005
#     type: L2



OptimizerBuilder:
  # clip_grad_by_norm: 1.0
  optimizer:
    type: AdamW
    weight_decay: 0.05

