_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
]

log_iter: 100
snapshot_epoch: 1
weights: output/zhao_gfl_coco_1x/model_final
find_unused_parameters: True


architecture: YOLOv3
pretrain_weights: /paddle/ResNet50_vd_dcn_db_obj365_pretrained.pdparams
norm_type: sync_bn
use_ema: true
ema_decay: 0.9998

YOLOv3:
  backbone: ResNet
  neck: PPYOLOFPN
  yolo_head: GFLHead
  post_process: ~

ResNet:
  depth: 50
  variant: d
  return_idx: [ 1, 2, 3 ]
  dcn_v2_stages: [ 3 ]
  freeze_at: -1
  freeze_norm: false
  norm_decay: 0.
  lr_mult_list: [ 0.5, 0.5, 0.5, 0.5 ]

PPYOLOFPN:
  drop_block: true
  block_size: 3
  keep_prob: 0.9
  spp: true

GFLHead:
  conv_feat:
    name: FCOSFeat
    feat_in: 256
    feat_out: 256
    num_convs: 4
    norm_type: "gn"
    use_dcn: false

  fpn_stride: [ 8, 16, 32 ]
  reg_max: 16
  use_yolo_neck: True
  loss_class:
    name: QualityFocalLoss
    use_sigmoid: True
    beta: 2.0
    loss_weight: 1.0
  loss_dfl:
    name: DistributionFocalLoss
    loss_weight: 0.25
  loss_bbox:
    name: GIoULoss
    loss_weight: 2.0
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 100
    score_threshold: 0.025
    nms_threshold: 0.6

epoch: 12

LearningRate:
  base_lr: 0.01
  schedulers:
  - !CosineDecay
    max_epochs: 12
    eta_min: 0.0005
  - !LinearWarmup
    start_factor: 0.001
    steps: 500

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2


worker_num: 2
TrainReader:
  sample_transforms:
  - Decode: {}
  - RandomFlip: {prob: 0.5}
  - Resize: {target_size: [800, 1333], keep_ratio: true, interp: 1}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  - Gt2GFLTarget:
      downsample_ratios: [8, 16, 32]
      grid_cell_scale: 8
  batch_size: 2
  shuffle: true
  drop_last: true

EvalReader:
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 1, target_size: [800, 1333], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  batch_size: 2
  shuffle: false

TestReader:
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 1, target_size: [800, 1333], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  batch_size: 1
  shuffle: false
