_BASE_: [
  'datasets/coco_instance.yml',
  '../runtime.yml',
  '_base_/optimizer_1x.yml',
  '_base_/detr_r50_segm.yml',
  '_base_/detr_segm_reader.yml',
]
weights: output/detr_r50_segm_1x_coco/model_final
