worker_num: 6
TrainReader:
  inputs_def:
    num_max_boxes: 100

  sample_transforms:
    - Decode: {}
    - RandomCrop: {}

    # - RandomResize: {target_size: [640], random_interp: True, keep_ratio: True}
    # - Mosaic: {target_size: 640, mosaic_border: [-320, -320]} #  # x y w h
    # - RandomPerspective: {degree: 0, translate: 0.1, scale: 0.5, shear: 0.0, perspective: 0.0, border: [-320, -320]} # x y w h
    - RandomResize: {target_size: [640], random_interp: True, keep_ratio: False}

    - RandomFlip: {prob: 0.5}
    - RandomHSV: {hgain: 0.015, sgain: 0.7, vgain: 0.4}
    - PadBox: {num_max_boxes: 100} # gt_num

  batch_transforms:
    # - BatchRandomResize: {target_size: [640], random_size: True, random_interp: True, keep_ratio: False}
    # - BboxXYXY2XYWH: {}
    - NormalizeBox: {}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - Gt2Yolov5Target: {anchor_masks: [[0, 1, 2], [3, 4, 5], [6, 7, 8]], anchors: [[10, 13], [16, 30], [33, 23], [30, 61], [62, 45], [59, 119], [116, 90], [156, 198], [373, 326]], downsample_ratios: [8, 16, 32]}

  mosaic_epoch: 10000
  batch_size: 4
  shuffle: true
  drop_last: true
  use_shared_memory: true


EvalReader:
  sample_transforms:
    - Decode: {}
    # - Resize: {target_size: [640, 640], keep_ratio: False, interp: 2}
    - LetterBox: {target_size: 640, rect: false, auto: false, augment: false}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1

TestReader:
  inputs_def:
    image_shape: [3, 640, 640]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: False, interp: 2}
    - LetterBox: {target_size: 640, rect: true, auto: false, augment: false}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1
