_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/gfl_r50_fpn.yml',
  '_base_/optimizer_1x.yml',
  '_base_/yolov5_reader.yml',
]

weights: output/fgl_mosaic_3x_coco/model_final
find_unused_parameters: True


epoch: 36

LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [24, 33]
  - !LinearWarmup
    start_factor: 0.1
    steps: 1500

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2
