_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/gfl_r50_pan.yml',
  '_base_/optimizer_1x.yml',
  '_base_/gfl_reader.yml',
]


weights: output/gfl_r50_pan_3x_coco/model_final
find_unused_parameters: True



epoch: 36

LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [24, 33]
  - !LinearWarmup
    start_factor: 0.1
    steps: 1500



# worker_num: 2
# TrainReader:
#   sample_transforms:
#   - Decode: {}
#   - RandomFlip: {prob: 0.5}
#   - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}  
#   - RandomResizeCrop: {resizes: [400, 500, 600], cropsizes: [[384, 600], ], prob: 0.5}
#   - RandomResize: {target_size: [[480, 1333], [512, 1333], [544, 1333], [576, 1333], [608, 1333], [640, 1333], [672, 1333], [704, 1333], [736, 1333], [768, 1333], [800, 1333]], keep_ratio: True, interp: 2}
#   - Permute: {}
#   batch_transforms:
#   - PadBatch: {pad_to_stride: 32}
#   - Gt2GFLTarget:
#       downsample_ratios: [8, 16, 32, 64, 128]
#       grid_cell_scale: 8
#   batch_size: 2
#   shuffle: true
#   drop_last: true
#   use_shared_memory: true
  