_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/gfl_r50_pan.yml',
  '_base_/optimizer_1x.yml',
  '_base_/gfl_reader.yml',
]

weights: output/gfl_r50_pan_1x_coco/model_final
find_unused_parameters: True
