metric: KITTI3D
num_classes: 3

# ├── kitti3d
# │   ├── ImageSets
# │   ├── testing
# │   │   ├── calib
# │   │   ├── image_2
# │   │   ├── velodyne
# │   ├── training
# │   │   ├── calib
# │   │   ├── image_2
# │   │   ├── label_2
# │   │   ├── velodyne
# https://github.com/traveller59/second.pytorch/tree/master/second/data/ImageSets



# wget -c  https://raw.githubusercontent.com/traveller59/second.pytorch/master/second/data/ImageSets/test.txt --no-check-certificate --content-disposition -O ./dataset/kitti3d/ImageSets/test.txt
# wget -c  https://raw.githubusercontent.com/traveller59/second.pytorch/master/second/data/ImageSets/train.txt --no-check-certificate --content-disposition -O ./dataset/kitti3d/ImageSets/train.txt
# wget -c  https://raw.githubusercontent.com/traveller59/second.pytorch/master/second/data/ImageSets/val.txt --no-check-certificate --content-disposition -O ./dataset/kitti3d/ImageSets/val.txt
# wget -c  https://raw.githubusercontent.com/traveller59/second.pytorch/master/second/data/ImageSets/trainval.txt --no-check-certificate --content-disposition -O ./dataset/kitti3d/ImageSets/trainval.txt


TrainDataset:
  !MonoKitti3d
    dataset_dir: dataset/kitti3d
    image_dir: training/
    anno_path: ImageSets/train.txt
    data_fields: ['image', 'label', 'calib', 'velodyne']

EvalDataset:
  !MonoKitti3d
    dataset_dir: dataset/kitti3d
    image_dir: training/
    anno_path: ImageSets/val.txt
    data_fields: ['image', 'label', 'calib', 'velodyne']

TestDataset:
  !MonoKitti3d
    dataset_dir: dataset/kitti3d
    image_dir: testing/
    anno_path: ImageSets/test.txt
    data_fields: ['image', 'calib', 'velodyne']
