
_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '../faster_rcnn/_base_/optimizer_swin_1x.yml',
  '../faster_rcnn/_base_/faster_rcnn_swin_tiny_fpn.yml',
  '../faster_rcnn/_base_/faster_rcnn_swin_reader.yml',
]
weights: output/faster_rcnn_swin_large_fpn_1x_coco/model_final


snapshot_epoch: 2

TrainReader:
  batch_size: 1

LearningRate:
  base_lr: 0.0001


SwinTransformer:
  embed_dim: 192
  depths:  [2, 2, 18, 2]
  num_heads: [ 6, 12, 24, 48 ]
  window_size: 7
  ape: false
  drop_path_rate: 0.4
  patch_norm: true
  out_indices: [0, 1, 2, 3]
  pretrained: https://bj.bcebos.com/v1/paddledet/models/pretrained/swin_large_patch4_window7_224_22k.params
