_BASE_: [
    '../datasets/coco_instance.yml',
    '../runtime.yml',
    'schedule_1x.yml',
    'reader.yml',
    '../cascade_rcnn/_base_/cascade_mask_rcnn_r50_fpn.yml',
]
weights: output/htc_r50_fpn_1x_coco/model_final


architecture: HybridTaskCascade
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_cos_pretrained.pdparams
#pretrain_weights: checkpoints/htc_r50_fpn_1x_coco_resnet.pdparams


convert_sync_bn: false
use_ema: false


HybridTaskCascade:
  backbone: ResNet
  neck: FPN
  rpn_head: RPNHead
  bbox_head: HybridTaskCascadeHead
  # mask_head: HybridTaskMaskHead
  fused_semantic_head: FusedSemanticHead
  # post process
  bbox_post_process: BBoxPostProcess
  mask_post_process: MaskPostProcess

ResNet:
  # index 0 stands for res2
  depth: 50
  norm_type: bn
  freeze_at: 0
  return_idx: [0,1,2,3]
  num_stages: 4

FPN:
  out_channel: 256

RPNHead:
  anchor_generator:
    aspect_ratios: [0.5, 1.0, 2.0]
    anchor_sizes: [[32], [64], [128], [256], [512]]
    strides: [4, 8, 16, 32, 64]
  rpn_target_assign:
    batch_size_per_im: 256
    fg_fraction: 0.5
    negative_overlap: 0.3
    positive_overlap: 0.7
    use_random: True
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 2000
    post_nms_top_n: 2000
    topk_after_collect: True
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 1000
    post_nms_top_n: 1000
  smoothl1loss: True
  smoothl1lossbetanume: 1.0
  smoothl1lossbetadeno: 9.0


HybridTaskCascadeHead:
  head: HybridTaskCascadeTwoFCHead
  roi_extractor:
    resolution: 7
    sampling_ratio: 0
    aligned: True
  semantic_roi_extractor:
    resolution: 14
    sampling_ratio: 0
    aligned: True
  bbox_assigner: BBoxAssigner
  mask_head: HybridTaskMaskHead
  smoothl1loss: True
  smoothl1lossbetanume: 1.0
  smoothl1lossbetadeno: 1.0

BBoxAssigner:
  batch_size_per_im: 512
  bg_thresh: 0.5
  fg_thresh: 0.5
  fg_fraction: 0.25
  cascade_iou: [0.5, 0.6, 0.7]
  use_random: True

HybridTaskCascadeTwoFCHead:
  out_channel: 1024

BBoxPostProcess:
  decode:
    name: RCNNBox
    prior_box_var: [30.0, 30.0, 15.0, 15.0]
  nms:
    name: MultiClassNMS
    keep_top_k: 100
#    score_threshold: 0.05
    score_threshold: 0.001
    nms_threshold: 0.5


HybridTaskMaskHead:
  head: HybridTaskMaskFeat
  roi_extractor:
    resolution: 14
    sampling_ratio: 0
    aligned: True
  semantic_roi_extractor:
    resolution: 14
    sampling_ratio: 0
    aligned: True
  mask_assigner: MaskAssigner
  share_bbox_feat: False

MaskFeat:
  num_convs: 4
  out_channel: 256

MaskAssigner:
  mask_resolution: 28

MaskPostProcess:
  binary_thresh: 0.5

FusedSemanticHead:
  semantic_num_class: 183

#architecture: HybridTaskCascade
#pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_cos_pretrained.pdparams
#
#HybridTaskCascade:
#  backbone: ResNet
#  neck: FPN
#  rpn_head: RPNHead
#  bbox_head: HTCBBoxHead # todo
#  mask_head: HTCMaskHead # todo
#  fused_semantic_head: FusedSemanticHead # todo
#  # post process
#  bbox_post_process: BBoxPostProcess
#  mask_post_process: MaskPostProcess
#
#ResNet:
#  # index 0 stands for res2
#  depth: 50
#  norm_type: bn
#  freeze_at: 0
#  return_idx: [0,1,2,3]
#  num_stages: 4
#
#FPN:
#  out_channel: 256
#
#RPNHead:
#  anchor_generator:
#    aspect_ratios: [0.5, 1.0, 2.0]
#    anchor_sizes: [[32], [64], [128], [256], [512]]
#    strides: [4, 8, 16, 32, 64]
#  rpn_target_assign:
#    batch_size_per_im: 256
#    fg_fraction: 0.5
#    negative_overlap: 0.3
#    positive_overlap: 0.7
#    use_random: True
#  train_proposal:
#    min_size: 0.0
#    nms_thresh: 0.7
#    pre_nms_top_n: 2000
#    post_nms_top_n: 2000
#    topk_after_collect: True
#  test_proposal:
#    min_size: 0.0
#    nms_thresh: 0.7
#    pre_nms_top_n: 2000
#    post_nms_top_n: 1000
#
#HTCBBoxHead:
#  head: CascadeTwoFCHead
#  roi_extractor:
#    resolution: 7
#    sampling_ratio: 0
#    aligned: True
#  bbox_assigner: BBoxAssigner
#
#BBoxAssigner:
#  batch_size_per_im: 512
#  bg_thresh: 0.5
#  fg_thresh: 0.5
#  fg_fraction: 0.25
#  cascade_iou: [0.5, 0.6, 0.7]
#  use_random: True
#
#CascadeTwoFCHead:
#  out_channel: 1024
#
#BBoxPostProcess:
#  decode:
#    name: RCNNBox
#    prior_box_var: [30.0, 30.0, 15.0, 15.0]
#  nms:
#    name: MultiClassNMS
#    keep_top_k: 100
#    score_threshold: 0.05
#    nms_threshold: 0.5
#
#
#HTCMaskHead:
#  head: MaskFeat
#  roi_extractor:
#    resolution: 14
#    sampling_ratio: 0
#    aligned: True
#  mask_assigner: MaskAssigner
#  share_bbox_feat: False
#
#MaskFeat:
#  num_convs: 4
#  out_channel: 256
#
#MaskAssigner:
#  mask_resolution: 28
#
#MaskPostProcess:
#  binary_thresh: 0.5
#
#
