metric: COCO
# num_classes: 80

TrainDataset:
  !PlainDetDataSet
    dataset_dir: dataset
    anno_path: ['coco/annotations/instances_train2017.json.csv',
                'obj365/annos/zhiyuan_objv2_train.json.csv', 
                'oid/annos/oidv6-train-annotations-bbox.csv-tmp.csv']

    data_fields: ['image', 'gt_bbox', 'gt_class',]
    use_cache: True


EvalDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: annotations/instances_val2017.json
    dataset_dir: dataset/coco
