_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_300e.yml',
  '_base_/yolov5_cspdarknet.yml',
  '_base_/yolov5_reader.yml',
]
weights: output/yolov5_s_coco/model_final

pretrain_weights: /paddle/PaddleDetection_yolov5/s.pdparams
depth_factor: 0.33
width_factor: 0.50

log_iter: 100
snapshot_epoch: 8

input_height: &input_height 640
input_width: &input_width 640
input_size: &input_size [*input_height, *input_width]

worker_num: 4
TrainReader:
#   inputs_def:
#     num_max_boxes: 120
  sample_transforms:
    - DecodeNormResize:
        target_size: *input_size
        keep_ratio: True
    - BboxPixelXYXY2NormCXCYWH: {}
    - MosaicPerspective: {mosaic_prob: 1.0, target_size: 640} #  # x y w h
#    - LetterBox: {target_size: 640, auto: False, scaleup: False}
    #- Albumentations: {}
    - RandomHSV: {hgain: 0.015, sgain: 0.7, vgain: 0.4}
    - RandomFlip: {}
    - BboxXYXY2XYWH: {}
    - NormalizeBox: {}
    - NormalizeImage: {mean: [0, 0, 0], std: [1, 1, 1], is_scale: True}
    - RGBReverse: {}
    - Permute: {}
#  batch_transforms:
#    - Gt2Yolov5Target:
#        anchor_masks: [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
#        anchors: [[10, 13], [16, 30], [33, 23],
#                  [30, 61], [62, 45], [59, 119],
#                  [116, 90], [156, 198], [373, 326]]
#        downsample_ratios: [8, 16, 32]
  batch_size: 8
  shuffle: True
  drop_last: True
  use_shared_memory: False
  collate_batch: False # False TODO
  mosaic_epoch: 300 #300


# EvalReader:
#   sample_transforms:
#     - Decode: {}
#     - LetterBox: {target_size: 640, auto: True, scaleup: True}
#     - NormalizeImage: {mean: [0, 0, 0], std: [1, 1, 1], is_scale: True}
#     - Permute: {}
#   batch_size: 1
EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *input_size, keep_ratio: True}
    - PadImage: {target_size: *input_size, fill_value: 114}
    - NormalizeImage: {mean: [0, 0, 0], std: [1, 1, 1], is_scale: True}
    - Permute: {}
  batch_size: 16


TestReader:
  inputs_def:
    image_shape: [3, 640, 640]
  sample_transforms:
    - Decode: {}
    - LetterBox: {target_size: [640, 640], auto: False, scaleup: False}
    - NormalizeImage: {mean: [0, 0, 0], std: [1, 1, 1], is_scale: True}
    - Permute: {}
  batch_size: 1


epoch: 300
LearningRate:
  base_lr: 0.01
  schedulers:
  - !YOLOV5LRDecay
    max_epochs: 300
    min_lr_ratio: 0.01
  - !ExpWarmup
    start_lr: 0.
    warmup_epochs: 3

OptimizerBuilder: # but no use, rewrite in trainer.py
  optimizer:
    momentum: 0.937
    type: Momentum
    use_nesterov: true
  regularizer:
    factor: 0.0005
    type: L2
