_BASE_:
  [
    "../datasets/coco_detection.yml",
    "../runtime.yml",
    "_base_/optimizer.yml",
    "_base_/yolov5x.yml",
    "_base_/yolov5_reader.yml",
  ]


# pretrain_weights: http://10.255.134.13:8091/cspdarknet53.pdparams


worker_num: 6
TrainReader:
  batch_size: 8


YOLOv5:
  backbone: CSPDarknet
  neck: YOLOv5FPN
  yolo_head: YOLOv3Head
  post_process: BBoxPostProcess

CSPDarknet:
  depth_multiple: 1.0
  width_multiple: 1.0

YOLOv5FPN:
  depth_multiple: 1.0
  width_multiple: 1.0
  feature_maps: [17, 20, 23]



snapshot_epoch: 1
weights: output/yolov5l_coco/model_final
