_BASE_:
  [
    "../datasets/coco_detection.yml",
    "../runtime.yml",
    "_base_/optimizer.yml",
    "_base_/yolov5x.yml",
    "_base_/yolov5_reader.yml",
  ]

snapshot_epoch: 5
weights: output/yolov5x_coco/model_final
