_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/sparse_rcnn_r50_fpn.yml',
  '_base_/optimizer_3x.yml',
  '_base_/sparsercnn_reader.yml',
]

#weights:  https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_cos_pretrained.pdparams # /root/paddlejob/workspace/output output